content/foundation/policies/conduct.md

👋 This PR updates a wording which had been introduced during copy-editing of the page.
I hope nothing is lost by changing the spelling to this.

fix: Typo in "Be Open" part of Code of Conduct

---

get_calendar.sh
pelicanconf.yaml

Add script to fetch calendar.md from SVN
Once this is working, calendar.md can be dropped from Git (and ignored?)

Fetch calendar from SVN

---

content/foundation/members.md

Update https://www.apache.org/foundation/members.html, adding new member Weiwei Yang.
Weiwei has already been listed here: http://home.apache.org/committers-by-project.html#member.

Add new member Weiwei Yang

---

content/security/committers.md

Some small clarifications:
* mention projects can request reviews of their CVE's before announcing
* promote (but not yet dictate) using the portal for sending the announcement emails
* no longer claim the CVE publication is the first point that any information is made public: the announcement is earlier.
* mention linking the CVE to the announcement and setting to `READY`

Clarify steps of the vulnerability disclosure process

---

content/foundation/members.md

Use https endpoint for struts.apache.org and some developer references.

Use https endpoint for struts.apache.org and developer references

---

content/legal/apply-license.md
content/legal/release-policy.md

As per agreement https://issues.apache.org/jira/browse/LEGAL-644 moving the page to under /legal/
Once this is merged, I'll ask INFRA to remove the page and update the re-direct.

Moving release-policy.md under /legal/ as per LEGAL-644

---

content/security/projects.md

Make it more obvious that this is a link to the
security page and not a generic link to the project page

Rename project security page column heading

---

content/.well-known/security.txt

As per https://www.rfc-editor.org/rfc/rfc9116
This makes it easier for security researchers to find out how to report potential issues to us.
Linking to https://www.apache.org/security/ instead of directly to our email addresses to encourage people to read about the ASF and our policies before engaging, and to somewhat avoid spam-y reports.
Hardcoding the expiry date is a bit awkward, but the whole point of that (required) field is to make sure someone reviews the information is still accurate from time to time, so confirming that by updating the expiry date might not be terrible (and the alternative, dynamically updating it somehow, seems worse).

Add `security.txt`

---

content/legal/generative-tooling.md

Small bugfix - I brainfarted and put the full title inside the {} rather than {{title}}.

Fixing title

---

content/legal/generative-tooling.md

i.e. original draft had 2(b), but the html generation for the site prefers the 2nd level of a numbered bullet to be (ii) rather than (b). Per report in #245

Fixing the reference within the list to match how the markdown ends up generated

---

content/index.ezmd

The intention of commit d44fc5b was to disable the Twitter card, however it has also caused the Blogs and Conference cards to disappear. Compare [1] and [2].
It seems that blank lines cause issues for commented-out code.
This patch removes the blank lines and aligns tags.
I have applied it to preview/tags to show that it works [3].
[1] https://www.apache.org/#latest-news
[2] https://www-previous.staged.apache.org/#latest-news
[3] https://www-tags.staged.apache.org/#latest-news

Blank lines affect output adversely

---

content/foundation/how-it-works/index.md

The section https://www-previous.staged.apache.org/foundation/how-it-works.html#documentation used to point to https://www-previous.staged.apache.org/dev/.
This has additional useful info which is not present in the new link, i.e. https://infra.apache.org/

Restore original link as it has more info

---

content/licenses/LICENSE-2.0.md

full text of the suggestion
```
The text version <https://www.apache.org/licenses/LICENSE-2.0.txt> and the HTML presentation <https://www.apache.org/licenses/LICENSE-2.0> of the Apache License, Version 2.0 have a difference in markup which I feel should be remedied. (I am aware that it’s the _text_ what counts, not indentation and such – still there is room for improvement.)
Section “4. Redistribution.” contains a list with four items/paragraphs, followed by a further paragraph, which says “You may add Your own copyright statement […]”. This text about the copyright statement is not part of the list in the text version of the license; instead, it follows the list. In the HTML document, the text has been made part of the fourth list item. This is semantically incorrect: it talks about …
```

Implement suggestion from Nico Roeser to press@

---

theme/apache/templates/base.html

Removing Trademark Policy menu item, due to redundancy with "Legal & Trademark" item and, accoridng to analytics, very few people are coming into the Trademark page via this menu item.

Remove "Trademark Policy" menu item

---

content/events/current-event.md

https://events.apache.org/x/current-event.html currently goes to apachecon.com, rather than the actual site for the next event. Change the redirect

Go directly to current event

---

.asf.yaml

These were implemented starting here:
https://github.com/apache/infrastructure-p6/blob/fe0691e702b6a24405bf32d1a80edfb20beebc2e/modules/subversion_server/files/authorization/asf-mailer.conf#L639

Missing commit emails

---

content/css/styles.css

Fixing issue [298](https://github.com/apache/www-site/issues/298)
The increased height of the header was causing anchor link targets to be covered.  I added a css fix to increase the offset of the target.
@bproffitt @loganloganlogan

adding link targret offset

---

content/404.ezmd
theme/apache/templates/siteindex.html

Does not make sense to include siteindex and 404 page in the search index

Exclude siteindex and 404 page from search results

---

content/dev/pmc-chair.md

Once published, this will replace foundation/officers/advice-for-new-pmc-chairs.txt and will aslo be referenced in the secretary's PMC Chair onboarding email template.
For more details about improvements to the onboarding process I'm making:
https://cwiki.apache.org/confluence/display/COMDEV/PMC+Chair+Onboarding+Change+Proposal

New PMC Chair onboarding document

---

content/foundation/glossary.md
content/foundation/mailinglists.md
content/legal/ramblings.md
content/security/committers.md

I couldn't find an authorative reference, but it seems markmail.org has been permanently shut down
https://news.ycombinator.com/item?id=37230221

Replace references to markmail.org with lists.apache.org

---

content/security/committers.md
content/security/index.md

Two changes:
1. Adding a link to security-discuss@ to the front page.
2. The page discussing the vulnerability reporting had two paragraphs at the end that had gotten orphaned. I've made a go at incorporating them into the main text.

Tweaking the security site

---

content/foundation/policies/conduct.md

Katia Rojas stepped down from her VP role a while ago.
I have also added links to https://whimsy.apache.org/foundation/orgchart in case we forget to update this page in the future when there are changes in these roles.

Remove VP D&I and add links to org chart

---

content/.htaccess

The rewrite is not necessary (indeed won't be triggered) as all requests have already been converted to https by the TLP container host.
For example, try the preview at:
http://www-nohttps.staged.apache.org/
Whilst it does not change the behaviour of the live site, having the rewrite makes local testing of htaccess files harder.
Local testing rarely uses or needs https, and it is complicated to set up.
Pelican has a server function, but that does not support htaccess files, and if it did, one would need to use https anyway.
Sample curl output:
$ curl -I http://www-nohttps.staged.apache.org/
HTTP/1.1 301 Moved Permanently
Date: Wed, 01 Nov 2023 13:03:49 GMT
Server: Apache
Location: https://www-nohttps.staged.apache.org/

HTTP=>HTTPS is done by container host

---

content/security/committers.md
content/security/index.md

Security folk set as reviewers. Please do not merge this without Security Committee approval.
Four proposed changes to the site.
1. I've made it more prominent that the ASF is a CNA.
2. Pointed to the security-discuss mailing list on the front page.
3. Adjusted the process language to make it more intentional - projects should use the default process, or must contact the security committee to review a different process. I think it's important for the security committee to be very aware of anyone not using the default process.
4. There were a couple of paragraphs at the end of the process that were out of context, or maybe originally footnotes. I've incorporated them into the text.

Security website updates

---

content/foundation/marks/pmcs.md

Allow Thanks to link to other 
`www.apache.org/foundation/thanks.html` or
`www.apache.org/foundation/sponsors.html`
The thanks.html is actually a redirect to sponsors.html.

Update pmcs.md to allow links to sponsors.html

---

content/index.ezmd

The home page has the word 'test' in a content title.
https://www.apache.org/#software-for-the-public-good-test

Removing 'test' from homepage title

---

content/ads/adserver.txt

Update the 'ad server' README to point to the new version, since this stuff hasn't been updated in the last few years, and so still points to older events.

Remove deprecated, broken documentation.

---

content/board/policies.md

This removes the draft marker and cleans up pointers to any well-recognized MUST links, which include some sort of board or specific policy-setting officer policy on them, versus some SHALL/MAY links which are best practices or similar.

Update board policies overview page

---

.asf.yaml

In https://github.com/apache/www-site/pull/362 we found intermediate merge commit can cause the commit history hard to read. Thus, I propose to leave only the "Squash and merge" button to make it clear that we always squash the whole PR into one commit on merging.

Keep only Squash and merge button

---

content/foundation/buy_stuff.md

As per @rbowen on #comdev Slack, the RedBubble store has been canceled.

Remove RedBubble store mention and links

---

pagefind.sh

The current version of pagefind is now quite old (1.0.3).
The preview looks OK to me:
https://www-pagefind110.staged.apache.org/

Update to latest version of pagefind (1.1.0)

---

content/history/data/directors.js
content/history/directors.md

This updates the director's timeline to the current roster, preview at https://www-directors2024.staged.apache.org/history/directors.html

Update directors data for 2024

---

content/board/policies.md
content/dev/pmc.md
content/dev/project-requirements.md
content/foundation/governance/pmcs.md

There were a few documentation links (in comdev site mainly) that lined to #newpmc anchor, and since the links were shown verbatim in the page, they could be misunderstood - it was not about new PMC but about new PMC menber, and since we are now reminding projects that they should not invite "new PMC" but "new PMC member", correcting it in the link is a good thing to do.
Separate PR in comdev site corrects those links (and changes them to be replaced with "New PMC member" name.

Correct the link for new PMC member to `newpmcmember` from `newpmc`

---

content/foundation/faq.md

The often asked question "Can I refer to an individual, organization or community as 'founding' an ASF project?" is currently on the Newsroom page. Because this is one of the more common brand violations that occur, it would make more sense to appear in the FAQ, which is a more logical place one might look. I'm proposing the addition to the FAQ, and will be proposing the deletion (and re-routing) to the Newsroom page if others agree. @markt-asf @justinmclean @bproffitt for input.

New marketing category and add "creator" FAQ

---

content/security/index.md

these are 'known not to be issues', so I think 'non-issues' fits better than 'known-issues'.
(this will break old links to this section, but in a pretty mild way)

security: better id for section on non-issues

---

content/foundation/leadership.ezmd

Preview at https://www-timelink.staged.apache.org/foundation/leadership
Adds a link from that page to /history/directors.html

Add Board timeline link to leadership page

---

content/index.ezmd

Updated the "cards" section with:
The Plus One newsletter (replacing the Community card as it's duplicative of the updated navigation).
And:
Updated copy for the Reports section to remove quarterly reports and other outdated info.
Updated Conferences card to focus on Community Over Code and replace the apachecon link with C/C link.
cc @bproffitt for approval

Add Plus One to homepage + other card updates

---

content/dev/pmc.md

Links to new committer invite template
Clarifies ICLA requirement
Links to new location of "new committers" document.

Tweaks to onboarding docs

---

content/licenses/contributor-agreements.md

The sentence "Send only one document (file plus signature) per email." was unclear to some readers. This change clarifies that each email should contain one complete document, including both the file and signature.
The updated sentence is:
"Please send only one complete document (file plus signature) in each email."
This revision ensures that contributors better understand how to submit their documents

Clarify sentence regarding document submission per email.

---

content/foundation/glossary.md
content/foundation/governance/meetings.md
content/foundation/voting.md

In bylaws 4.1, it writes (https://www.apache.org/foundation/bylaws.html#4.1):
> ... members of the corporation shall be admitted as members of the corporation only by a majority vote of the existing members of the corporation ...
And our glossary writes (https://www.apache.org/foundation/glossary.html#MajorityApproval):
> Majority Approval
> Refers to a [vote](https://www.apache.org/foundation/glossary.html#Vote) (sense 1) which has completed with at least three binding +1 votes and more +1 votes than -1 votes.
So I'd try to keep the expression in sync to eliminate confusion. Not sure if it's a simple fact check or we should bring a discussion to the list.
cc @jvz

Improve reference to voting rules from the voting process page

---

content/legal/release-policy.md

The following discussions on members@ talked about urgent releases where the voting period was less than the normal 72 hours:
- https://lists.apache.org/thread/v6ypw13s1r3zc6xmvbl10mzfgbcjw4xf
- https://lists.apache.org/thread/ks9r0t3x8w5k5fy707dhphgnt2k7j7nd
It is difficult to have a consensus on what an _exceptional_ circumstance is. No-one has disagreed with urgent releases for publicly know security issues. However there was agreement from a number of people (and no disagreement) on the following points:
- Explain why in the vote email
- give project members as much "heads up" as possible before the vote is called
- since its not following normal policy it must be reported to the board
I've tried to encapsulate that in a new section in the release policy doc. However I'm not the best …

Add a section on "Expedited Releases" to the Release Policy

---

.asf.yaml

No need for minimum_page_count work-round any more
Drop profile from publish stanza (no longer tolerated by parser) 
Fix link to documentation
The recent .asf.yaml parser change caused various issues, which I hope have all been sorted now.
This PR is to remove the temporary work-round (reversion to the old parser).

Tidy up .asf.yaml to allow for recent parser changes

---

content/board/services.md
content/dev/infrastructure.md
content/dev/pmc.md
content/foundation/.htaccess
content/foundation/how-it-works/index.md

home is an alias for people, but is deprecated as a name. This is because it is not longer avaliable as a home for user files

home.a.o => people.a.o

---

content/foundation/leadership.ezmd

Fixes the leadership page ezt to handle moving of officers. There is an anomaly in the `committee-info.json` that is produced and several officers were moved from `roster` to `chair`

Update leadership.ezmd after committee-info changes

---

content/licenses/contributor-agreements.md

Secretary does not accept mismatched emails - email sender must match email in PDF.

Secretary does not accept mismatched emails

---

content/foundation/marks/index.ezmd
content/foundation/policies/conduct.ezmd

Replaced current names of president and vp with references to variables, so no need to update the page on every change
See https://www-sebb-usevars.staged.apache.org/foundation/policies/conduct#reporting-guidelines

Convert to ezmd so can reference variables for roles

---

content/dev/index.md

Mailing lists section had long-gone mailiing list information. This brings it up to current practice.

Corrects out-of-date mailing list information

---

data/eccn/eccnmatrix.yaml

URLs referring to the host dist.apache.org should not be used for source references they are not permanent and not intended for external use

Fix pirk URL

---

asfdata.yaml
content/dev/project-requirements.md
content/foundation/marks/guide.md
content/foundation/marks/templates/product-misuse.md
content/foundation/press/index.md
content/free/index.md
content/index.ezmd
content/press/boilerplate/index.md
content/press/media.md

Fixed counts have been replaced with variable derived from asfdata.yaml in the following pages:
https://www-sebb-counts.staged.apache.org/
https://www-sebb-counts.staged.apache.org/dev/project-requirements 
https://www-sebb-counts.staged.apache.org/free 
https://www-sebb-counts.staged.apache.org/press/boilerplate
 https://www-sebb-counts.staged.apache.org/press/media
This ensures that the counts on different pages don't get out of sync, and avoids the need for regular page updates.

Replace fixed counts with asfdata variables
