apache/www-site

pelicanconf.py

There are no longer any mdsnippet files

---

asfdata.yaml
data/eccn/eccnmatrix.yml
theme/plugins/asfdata.py

Translated from json using https://onlineyamltools.com/convert-json-to-yaml.
The python scripts look pretty brittle.  I didn't try this out, totally untested.
The top level eccnmatrix object is unnecessary, but I didn't want to track down how the imported data is used so I left it as a plain translation.

supply an eccnmatrix.yml translation and adjust to use it

---

content/legal/release-policy.md

further edits related to the end of the mirror system

Mirror edits

---

content/security/committers.md

Revert "Update committers.md"

---

content/foundation/members.md

This PR adds juzhiyuan to the members' list.

docs: update members list

---

content/dev/service_unavailable.html

The current link does not make much sense IMHO
I hope this helps!

Fix link to Slack

---

content/press/index.md

Thought I had updated this a while back, but doing so now.

Editing to reflect current status.

---

content/css/styles.css
theme/apache/templates/base.html

content by @loganloganlogan
- Removing "support apache" icon
- removing heading " Community-led development "The Apache Way"
@bproffitt Please Review

Base updates

---

content/legal/resolved.md

https://issues.apache.org/jira/browse/LEGAL-638

Adding LBNL per LEGAL-638

---

content/research/index.md

See discussion on press@; feel free to edit for style/clarity.

Add Research Information Portal page

---

content/foundation/board/reporting.md

I'll point the Board members to this to get their approval.
Preview at https://www-projectstates.staged.apache.org/foundation/board/reporting

Add project states to the PMC reporting page, as discussed on board@

---

pagefind.sh
pelicanconf.yaml
theme/apache/templates/base.html

Requires postrun plugin, see:
https://github.com/apache/infrastructure-pelican/pull/54

Add pagefind search button

---

content/legal/release-policy.md
content/legal/src-headers.md

See discussion here https://issues.apache.org/jira/browse/LEGAL-647

Updating policy as per LEGAL-647 and LEGAL-646

---

content/foundation/individual-supporters.md

Removing unneeded p tag per #223

Removing unneeded p tag per #223

---

content/foundation/leadership.ezmd

Per earlier board resolution and per request.

Add VP Public Affairs

---

content/foundation/contact.md

Adding section for Academic Researchers as noted in https://github.com/apache/www-site/issues/271
@bproffitt

Add Academic Researchers section to Contacts page

---

content/index.ezmd

Does not make sense to index the dynamic data from random projects.

Ignore dynamic (random) project data

---

content/board/index.md
content/board/policies.md

Ensure changes copied from paulau to main don't revert previous updates to main

Sync with main

---

content/foundation/sponsorship.md

Copy drafted based on a conversation with Sally Khudairi, VP Sponsor Relations. Copying @bobpaulin for review and approval, as well as @bproffitt as FYI.

Add description about benefits to the Targeted Sponsorship section

---

content/foundation/mailinglists.md

It's more likely that readers will want to subscribe to a project list, so show that syntax

Give more relevant project example

---

content/security/committers.md
content/security/index.md

Reverts apache/www-site#318 This was not reviewed by security committee and was mistakenly pushed through by bkp.

Revert "Tweaking the security site"

---

content/events/README.txt

Update the event promotional image documentation to reflect reality. Remove links to content that is incorrect, missing, or otherwise not maintained.

Update to reflect the current status of these event promotional images.

---

theme/apache/templates/base.html

@bproffitt @loganloganlogan 
Swapping out the header CTA to "Make a Donation"

Update Header CTA - Make a Donation

---

theme/apache/templates/base.html

@loganloganlogan  @bproffitt 
Swapped out the Donation button for the Sponsor ASF button.

Header CTA change

---

content/foundation/docs/targeted-sponsorship-policy.md
content/foundation/sponsorship.md

Converts to HTML, and fixes a handful of internal links that have been superceded, or have been moved in the past 5 years.

Converts legacy PDF file to HTML. Fixes links.

---

content/foundation/docs/targeted-sponsorship-policy.md

Improve link text and rendering

---

content/foundation/members.md

Saves a clicks, clicking on the "edit this page" link will now navigate directly to the in browser editor

Edit link on members.md will now directly edit page

---

content/dev/service_unavailable.html

Avoid 'innerHTML'

---

content/css/new-ui.css
theme/apache/templates/base.html

**Updating the Navigation bar**
**Change the menu items**
here I make the menu items little bigger, and give it a round edges for a modern look
**Add a dropdown arrow animation, and style the submenus**
- Add an animation to the dropdown menu. whenever a click will occur the arrow will rotate upward, after the focus is removed it will come back to it's original state.
- Add some spacing between the sub menus, so they will be more accessible.

Change the look of navigation and give some final touches

---

content/index.ezmd

@bproffitt @loganloganlogan 
Please review. I replaced the main site banner with the 25 year anniversary banner.

Adding 25 year anniversary banner to home page

---

content/foundation/members.md

Add myself (Andriy Redko) into members list

Add Andriy Redko into members list

---

content/foundation/members.md

Add myself (Lukas Ott) into members list

Add Lukas Ott into members list

---

content/asf25years/index.ezmd

@bproffitt @loganloganlogan Updating a link on the 25 year anniversary page

Updating public good form link

---

theme/apache/templates/base.html

Proposed fix for 372

---

content/foundation/glossary.md

According to https://lists.apache.org/thread/8lmb8o7bsr7wyqyfwqpw3pgsztxl9h0s, make a draft to update the glossary.

Update glossary for Incubator-related terms

---

content/.well-known/security.txt

It should expire less than a year in the future

Reconfirm the security.txt, update expiration date

---

.github/workflows/members_check.yml
content/foundation/members.md
members_check.py

As can be seen from the test runs, the script detected a misplaced emeritus entry [1], as well as its correction [2]
[1] https://github.com/apache/www-site/actions/runs/10147534216
[2] https://github.com/apache/www-site/actions/runs/10147571726

Add script to check changes to members.md

---

content/dev/index.md

paste.a.o is no longer online.

Remove mention of paste.a.o

---

content/css/styles.css

@bproffitt  @loganloganlogan 
This is the fix for the main search, take 2.  Apologies for the earlier attempt.

Issue  #406 fix - main search

---

content/history/data/directors.js

Preview at https://www-add-kanchana.staged.apache.org/history/directors.html
Updates directors data with the current change from cdutz to kanchana

Add directors change to timeline, cdutz -> kanchana

---

content/foundation/board/meeting.md

Allow a direct link in order to attend the meeting

---

theme/apache/templates/base.html

Changing CTA in header from Sponsor to Donate for the month of November.
@bproffitt @loganloganlogan

changing sponsorship button to donate

---

content/legal/release-policy.md

Drop the reference to SHA-1, as it is deprecated.

SHA-1 is deprecated

---

theme/apache/templates/base.html

This fixes #412 
Preview: https://www-issue412.staged.apache.org/

Move to input area when opening search

---

content/dev/pmc.md

Fix bad link new_pmc_chair

---

content/foundation/leadership.ezmd

Update leadership.ezmd - Tooling is a Corporate Officer

---

content/.well-known/security.txt

https://security.apache.org/report/ makes it clearer what to do when you want to report an issue with the ASF infrastructure, dependencies, or in our own code.

Point security.txt to more 'guided' reporting instructions

---

data/eccn/eccnmatrix.xml
data/eccn/eccnmatrix.yaml

Fixed some typos in XML and YAML files

misc(data/eccn): fix spelling

---

data/eccn/eccnmatrix.xml
data/eccn/eccnmatrix.yaml

data/eccn: fix spelling in XML and YAML files

---

content/dev/pmc.md

PMCs should contact Infra for svn auth tweaks.

---

content/foundation/board/meeting.md

See this email on board mailing list https://lists.apache.org/thread/3gj8b672979dfwt1d1g9m1r94brqb2xc

Add invited guests 

---

content/foundation/governance/board-charter.md

There are no links to this page yet, I'd do that in another PR.

Add board charter

---

content/index.ezmd

@loganloganlogan @bproffitt 
Hiding Sponsors section from the home page of the site.

Hiding sponsors section on home page

---

asfdata.yaml
content/index.ezmd

Add more counts to asfdata
Revert front page to total members, not just active
See: https://www-sebb-count2.staged.apache.org/

Member stats update

---

content/css/styles.css
theme/apache/templates/base.html

@loganloganlogan @bproffitt Adding underlines to table links

accessibility upgrades
